import Navbar from '@/components/Navbar';
import './globals.css';
import Profile from '@/components/Profile';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'AN OLD Legend',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-slate-800 text-white/90'>
      <div className='min-h-screen pb-16'>
        <Navbar />
        <Profile />
        {children}
      </div>
      <Footer />
      </body>
    </html>
  )
}
